name: awear
description: "Medical Dashboard Partnered with a Wireless Biometric Bracelet"
publish_to: 'none'
version: 0.8.0+1

environment:
  sdk: '>=3.10.0 <4.0.0' # Targets Dart 3.10+ / Flutter 3.38+

flutter:
  uses-material-design: true

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^7.0.0

  # State Management (Riverpod v2.6 is the stable choice for Isar v3)
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.3.5

  # Database
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1 # For Mobile
  path_provider: ^2.1.2

  # Serial Communication
  flutter_libserialport: ^0.6.0 # For Desktop (Windows)
  usb_serial: ^0.5.2 # For Mobile (Android OTG)

  # UI & Charts
  fl_chart: ^1.1.1
  intl: ^0.20.2 # For Date Formatting
  gap: ^3.0.0 # For easier layout spacing

  # Data Parsing
  json_annotation: ^4.9.0
  shared_preferences: 2.5.4

  # Firebase
  firebase_core: ^3.0.0
  cloud_firestore: ^5.0.0
  firebase_auth: ^5.0.0

  # Additional
  english_words: ^4.0.0  # For generating wordphrases like "happy-lion"
  badges: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  build_runner: 2.4.13  
  isar_generator: 3.1.0+1
  riverpod_generator: 2.4.0 
  json_serializable: 6.8.0

  analyzer: ">=5.13.0 <6.0.0"